apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-p7pw
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-p7pw
    app.kubernetes.io/part-of: cin4s-839-0091-app
  name: devfile-sample-p7pw
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-p7pw
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-p7pw
    spec:
      containers:
      - image: quay.io/stonesoup_perfscale/cin4s-839-0091-tenant/cin4s-839-0091-app/devfile-sample-p7pw@sha256:5fe0084de9b6c7e8f0fbbc2976017282f9cce62a49eff6faf6ae699a9aa0ca23
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
